SELECT ANIMAL_ID, NAME FROM ANIMAL_OUTS
WHERE ANIMAL_OUTS.ANIMAL_ID NOT IN
(
    SELECT ANIMAL_INS.ANIMAL_ID FROM ANIMAL_INS
    INNER JOIN ANIMAL_OUTS ON ANIMAL_OUTS.ANIMAL_ID = ANIMAL_INS.ANIMAL_ID
)
ORDER BY ANIMAL_ID