-- 년, 월, 성별 별로 상품을 구매한 회원수를 집계하는 SQL문
-- 년, 월, 성별을 기준으로 오름차순 정렬
SELECT YEAR(SALES_DATE) AS YEAR, MONTH(SALES_DATE) AS MONTH, GENDER, COUNT(DISTINCT(USER_INFO.USER_ID)) AS USERS FROM ONLINE_SALE
INNER JOIN USER_INFO ON ONLINE_SALE.USER_ID = USER_INFO.USER_ID
WHERE GENDER IN (0,1)
GROUP BY YEAR, MONTH, GENDER
ORDER BY YEAR, MONTH, GENDER