-- 년 월 설별로 상품을 구매한 회원 수 집계
SELECT YEAR(SALES_DATE) AS YEAR, MONTH(SALES_DATE) AS MONTH, GENDER, COUNT(DISTINCT(ONLINE_SALE.USER_ID)) AS USERS 
FROM ONLINE_SALE
INNER JOIN USER_INFO ON ONLINE_SALE.USER_ID = USER_INFO.USER_ID
WHERE GENDER IN (0,1)
GROUP BY YEAR, MONTH, GENDER
ORDER BY YEAR, MONTH, GENDER