-- 우유(Milk)와 요거트(Yogurt)를 동시에 구입한 장바구니
SELECT CART_ID FROM 
(SELECT DISTINCT(CART_ID) FROM CART_PRODUCTS
WHERE NAME = "Yogurt"
UNION ALL
SELECT DISTINCT(CART_ID) FROM CART_PRODUCTS
WHERE NAME = "Milk") AS T
GROUP BY CART_ID
HAVING COUNT(*) = 2
ORDER BY CART_ID