-- 우유와 요더트를 동시에 구입한 장바구니가 있는지 알아보고 있다면 아이디 조회
-- 아이디 순
SELECT CART_ID FROM (SELECT * FROM CART_PRODUCTS
WHERE NAME = "Milk"
GROUP BY CART_ID

UNION ALL

SELECT * FROM CART_PRODUCTS
WHERE NAME = "Yogurt"
GROUP BY CART_ID) AS T
GROUP BY CART_ID
HAVING COUNT(NAME) >= 2
ORDER BY CART_ID