SELECT FOOD_TYPE, REST_ID, REST_NAME, MAX(FAVORITES) AS FAVORITES FROM REST_INFO
INNER JOIN (SELECT FOOD_TYPE AS FT, MAX(FAVORITES) AS FAV FROM REST_INFO GROUP BY FOOD_TYPE) 
           AS NEW ON REST_INFO.FOOD_TYPE = NEW.FT AND REST_INFO.FAVORITES= NEW.FAV
GROUP BY FOOD_TYPE
ORDER BY FOOD_TYPE DESC