-- 1:21
-- 온라인 상품 판매정보, 오프라인 상품 판매 정보
-- 2022년 3월 오프라인/온라인 상품 판매 데이터, UNION ALL
-- 판매일, ID, USER ID 오름차순
SELECT DATE_FORMAT(SALES_DATE, "%Y-%m-%d") AS SALES_DATE, PRODUCT_ID, USER_ID, SALES_AMOUNT FROM (
    SELECT SALES_DATE, PRODUCT_ID, USER_ID, SALES_AMOUNT FROM ONLINE_SALE 
    UNION ALL
    SELECT SALES_DATE, PRODUCT_ID, NULL AS USER_ID, SALES_AMOUNT FROM OFFLINE_SALE) AS TOTAL
WHERE DATE_FORMAT(SALES_DATE, "%m") = "03"
ORDER BY SALES_DATE, PRODUCT_ID, USER_ID