SELECT ANIMAL_OUTS.ANIMAL_ID,ANIMAL_OUTS.ANIMAL_TYPE, ANIMAL_OUTS.NAME FROM ANIMAL_OUTS
LEFT JOIN ANIMAL_INS ON ANIMAL_INS.ANIMAL_ID = ANIMAL_OUTS.ANIMAL_ID
WHERE 
((SEX_UPON_INTAKE NOT LIKE "%Spayed%") AND (SEX_UPON_INTAKE NOT LIKE "%Neutered%")) 
AND
((SEX_UPON_OUTCOME LIKE "%Spayed%") OR (SEX_UPON_OUTCOME LIKE "%Neutered%"))
ORDER BY ANIMAL_OUTS.ANIMAL_ID