-- 7:53
-- 완료된 중고 거래의 총 금액이 70만원 이상인 사람
-- 회원 ID 닉네임 총거래금액 조회
-- 총 거래금액을 기준으로 오름차순 정렬

SELECT USED_GOODS_USER.USER_ID, NICKNAME, TOTAL_SALES FROM USED_GOODS_USER
INNER JOIN
(SELECT WRITER_ID, SUM(PRICE) AS TOTAL_SALES FROM USED_GOODS_BOARD
WHERE STATUS = "DONE"
GROUP BY WRITER_ID
HAVING SUM(PRICE) >= 700000) AS T
ON USED_GOODS_USER.USER_ID = T.WRITER_ID
ORDER BY TOTAL_SALES