-- 12:58
-- 가격이 제일 비싼 식품
-- 과자 국 김치 식용유
-- 식품 가격 내림차순

SELECT T.CATEGORY, MAX_PRICE, PRODUCT_NAME FROM FOOD_PRODUCT
INNER JOIN 
(SELECT CATEGORY, MAX(PRICE) AS MAX_PRICE FROM FOOD_PRODUCT
WHERE CATEGORY IN ("과자", "국", "김치", "식용유")
GROUP BY CATEGORY) AS T ON FOOD_PRODUCT.CATEGORY = T.CATEGORY
WHERE PRICE = MAX_PRICE
ORDER BY MAX_PRICE DESC