-- 식품 분류별 제일 비싼 식품의 분류 가격 이름 조회
-- 과자 국 김치 식용유
-- 식품가격 기준 내림차순

-- 식품 분류 별 제일 비싼 식품을 찾아야 함

SELECT T.CATEGORY, T.PRICE AS MAX_PRICE, PRODUCT_NAME FROM FOOD_PRODUCT
INNER JOIN 
(SELECT CATEGORY, MAX(PRICE) AS PRICE FROM FOOD_PRODUCT
WHERE CATEGORY IN ('과자', '국', '김치', '식용유')
GROUP BY CATEGORY) AS T ON T.CATEGORY = FOOD_PRODUCT.CATEGORY
WHERE T.PRICE = FOOD_PRODUCT.PRICE
ORDER BY MAX_PRICE DESC