SELECT FOOD_PRODUCT.CATEGORY, MP AS MAX_PRICE, PRODUCT_NAME FROM FOOD_PRODUCT
INNER JOIN (SELECT CATEGORY, MAX(PRICE) AS MP FROM FOOD_PRODUCT
WHERE CATEGORY IN ("식용유", "김치", "국", "과자")
GROUP BY CATEGORY) AS T ON T.CATEGORY = FOOD_PRODUCT.CATEGORY
WHERE PRICE = MP
ORDER BY MAX_PRICE DESC