-- 리뷰를 가장 많이 작성한 회원의 리뷰들을 조회
-- 가장 많은 리뷰수 조회
-- 가장 많은 리뷰를 단 회워 조회
-- 회원의 리뷰들 조회

SELECT MEMBER_NAME, REVIEW_TEXT, DATE_FORMAT(REVIEW_DATE, "%Y-%m-%d") AS REVIEW_DATE FROM REST_REVIEW
INNER JOIN MEMBER_PROFILE ON REST_REVIEW.MEMBER_ID = MEMBER_PROFILE.MEMBER_ID
WHERE MEMBER_PROFILE.MEMBER_ID IN 
(SELECT MEMBER_ID FROM REST_REVIEW
GROUP BY MEMBER_ID
HAVING COUNT(*) = (SELECT COUNT(*) AS CNT FROM REST_REVIEW
GROUP BY MEMBER_ID
ORDER BY CNT DESC
LIMIT 1))
ORDER BY REVIEW_DATE, REVIEW_TEXT