-- 1:10
-- 리뷰를 가장 많이 작성한 회원의 리뷰들을 조회
-- 회원 이름, 리뷰 텍스트, 리뷰 작성일
-- 리뷰 작성일 오름차순, 리뷰텍스트 오름차순

SELECT MEMBER_NAME, REVIEW_TEXT, REVIEW_DATE
FROM (SELECT REST_REVIEW.MEMBER_ID, REVIEW_TEXT, DATE_FORMAT(REVIEW_DATE, "%Y-%m-%d") AS REVIEW_DATE FROM REST_REVIEW
WHERE MEMBER_ID IN
(SELECT MEMBER_ID FROM REST_REVIEW
GROUP BY MEMBER_ID
HAVING COUNT(*) = (SELECT COUNT(*) AS MC FROM REST_REVIEW
GROUP BY MEMBER_ID
ORDER BY MC DESC
LIMIT 1))) AS F
LEFT JOIN MEMBER_PROFILE ON MEMBER_PROFILE.MEMBER_ID = F.MEMBER_ID
ORDER BY REVIEW_DATE, REVIEW_TEXT