SELECT BK.AUTHOR_ID, BK.AUTHOR_NAME, 
CATEGORY, SUM(SALES*PRICE) AS TOTAL_SALES FROM BOOK_SALES
INNER JOIN
(SELECT BOOK.BOOK_ID, AUTHOR.AUTHOR_NAME, AUTHOR.AUTHOR_ID, CATEGORY, PRICE FROM BOOK
 INNER JOIN AUTHOR ON BOOK.AUTHOR_ID = AUTHOR.AUTHOR_ID)
 AS BK ON BOOK_SALES.BOOK_ID = BK.BOOK_ID
WHERE MONTH(SALES_DATE) = 1
GROUP BY BK.AUTHOR_ID, BK.CATEGORY
ORDER BY BK.AUTHOR_ID, BK.CATEGORY DESC