-- 2022년 1월, 저자별, 카테고리별 매출액(판매량 * 판매가)
SELECT AUTHOR_ID, AUTHOR_NAME, CATEGORY, SUM(SALES*PRICE) AS TOTAL_SALES FROM BOOK_SALES
INNER JOIN
(SELECT BOOK_ID, CATEGORY, BOOK.AUTHOR_ID, PRICE, AUTHOR_NAME FROM BOOK
INNER JOIN AUTHOR ON BOOK.AUTHOR_ID = AUTHOR.AUTHOR_ID) 
AS T ON T.BOOK_ID = BOOK_SALES.BOOK_ID
WHERE DATE_FORMAT(SALES_DATE, "%Y-%m") = "2022-01"
GROUP BY AUTHOR_ID, CATEGORY
ORDER BY AUTHOR_ID, CATEGORY DESC