-- 저자 별, 카테고리 별 = ORDER BY
-- ((BOOK, AUTHOR = 1:1 조인), BOOK_SALES = 1:N 조인)
SELECT AUTHOR_ID, AUTHOR_NAME, CATEGORY, SUM(SALES*PRICE) AS TOTAL_SALES
FROM BOOK_SALES
INNER JOIN 
    (SELECT BOOK_ID, CATEGORY, BOOK.AUTHOR_ID, PRICE, AUTHOR_NAME FROM BOOK
     INNER JOIN AUTHOR ON BOOK.AUTHOR_ID = AUTHOR.AUTHOR_ID) AS T
     ON BOOK_SALES.BOOK_ID = T.BOOK_ID
WHERE DATE_FORMAT(SALES_DATE, "%Y-%m") = "2022-01"
GROUP BY AUTHOR_ID, CATEGORY
ORDER BY AUTHOR_ID, CATEGORY DESC