SELECT 
FOOD_ORDER.PRODUCT_ID AS PRODUCT_ID, 
FOOD_PRODUCT.PRODUCT_NAME AS PRODUCT_NAME, 
(SUM(FOOD_ORDER.AMOUNT) * FOOD_PRODUCT.PRICE) AS TOTAL_SALES
FROM FOOD_ORDER
INNER JOIN FOOD_PRODUCT ON FOOD_ORDER.PRODUCT_ID = FOOD_PRODUCT.PRODUCT_ID
WHERE MONTH(PRODUCE_DATE) = 5
GROUP BY PRODUCT_ID
ORDER BY TOTAL_SALES DESC, PRODUCT_ID