-- 2022년 4월 13일 취소X인 CS 진료예약 내역 조회
-- 진료예약번호, 환자이름, 환자번호, 진료과코드, 의사이름, 진료예약일시
-- 진료예약일시를 기준으로 오름차순
SELECT APNT_NO, PT_NAME, T.PT_NO, MCDP_CD, DR_NAME, APNT_YMD FROM 
(SELECT APNT_YMD, APNT_NO, PT_NO, APPOINTMENT.MCDP_CD, DR_NAME FROM APPOINTMENT
INNER JOIN DOCTOR ON DOCTOR.DR_ID = APPOINTMENT.MDDR_ID
WHERE (DATE_FORMAT(APNT_YMD, "%Y-%m-%d") = "2022-04-13") AND (APNT_CNCL_YN = "N") AND (APPOINTMENT.MCDP_CD = "CS")) AS T
INNER JOIN PATIENT ON PATIENT.PT_NO = T.PT_NO
ORDER BY APNT_YMD