-- 2022년 4월 13일 취소되지 않은 CS 진료 예약 내역
-- 진료 예약 번호, 환자 이름, 환자 번호, 진료과 코드, 의사 이름, 진료 예약 일시
-- 진료 예약 일시 오름차순
SELECT APNT_NO, PT_NAME, PT_NO, T.MCDP_CD, DR_NAME, APNT_YMD
FROM (SELECT APNT_YMD, APNT_NO, PT_NAME, PATIENT.PT_NO, MCDP_CD, MDDR_ID FROM APPOINTMENT
INNER JOIN PATIENT ON PATIENT.PT_NO = APPOINTMENT.PT_NO
WHERE DATE_FORMAT(APNT_YMD, "%Y-%m-%d") = "2022-04-13" AND MCDP_CD = "CS" AND APNT_CNCL_YN = "N") AS T
LEFT JOIN DOCTOR ON DOCTOR.DR_ID = T.MDDR_ID
ORDER BY APNT_YMD