-- 2022년 4월 13일 취소 X, CS 진료 예약 내역 조회
SELECT APNT_NO, PT_NAME, PATIENT.PT_NO, MCDP_CD, DR_NAME, APNT_YMD 
FROM (SELECT DR_NAME, APPOINTMENT.MCDP_CD, APNT_YMD, PT_NO, APNT_NO FROM APPOINTMENT
INNER JOIN DOCTOR ON DOCTOR.DR_ID = APPOINTMENT.MDDR_ID
WHERE DATE_FORMAT(APNT_YMD,"%Y-%m-%d") = "2022-04-13" 
    AND APPOINTMENT.MCDP_CD = "CS" 
    AND APNT_CNCL_YN = "N") AS T
INNER JOIN PATIENT ON PATIENT.PT_NO = T.PT_NO
ORDER BY APNT_YMD