-- 식당 ID, 식당 이름, 음식 종류, 즐겨찾기수, 주소, 리뷰 평균 점수
-- 리뷰 평균점수는 소수점 세 번째 자리에서 반올림 0
-- 평균점수를 기준으로 내림차순, 즐겨찾기 수 내림차순
SELECT T.REST_ID, REST_NAME, FOOD_TYPE, FAVORITES, ADDRESS, SCORE FROM REST_INFO
INNER JOIN (SELECT REST_ID, ROUND(SUM(REVIEW_SCORE)/COUNT(REVIEW_SCORE), 2) AS SCORE FROM REST_REVIEW
GROUP BY REST_ID) AS T ON T.REST_ID = REST_INFO.REST_ID
WHERE ADDRESS LIKE ("서울%")
ORDER BY SCORE DESC, FAVORITES DESC