-- 1/8
-- 식당 정보 테이블, 식당 리뷰 테이블
-- 조건
-- 서울에 위치
-- 평균점수 소수 3번째에서 반올림
-- 평균점수 내림차순, 즐겨찾기수 내림차순
-- 식당 ID, 식당 이름, 음식 종류, 즐겨찾기 수, 주소, 리뷰 평균 점수 조회

SELECT REST_INFO.REST_ID, REST_NAME, FOOD_TYPE, FAVORITES, ADDRESS, ROUND(SUM(REVIEW_SCORE)/COUNT(REVIEW_SCORE),2)
AS SCORE FROM REST_INFO
INNER JOIN REST_REVIEW ON REST_INFO.REST_ID = REST_REVIEW.REST_ID
WHERE ADDRESS LIKE "서울%"
GROUP BY REST_INFO.REST_ID
ORDER BY SCORE DESC, FAVORITES DESC