-- 식당 ID, 이름, 종류, 즐겨찾기, 주소, 리뷰 평균 점수
SELECT REST_REVIEW.REST_ID, REST_NAME, FOOD_TYPE, FAVORITES, ADDRESS, 
ROUND(SUM(REVIEW_SCORE)/COUNT(REVIEW_SCORE), 2) AS SCORE
FROM REST_REVIEW
INNER JOIN REST_INFO ON REST_REVIEW.REST_ID = REST_INFO.REST_ID
WHERE ADDRESS LIKE "서울%"
GROUP BY REST_REVIEW.REST_ID
ORDER BY SCORE DESC, FAVORITES DESC